name: etcd
version: '3.1+master'
summary: Resilient key-value store by CoreOS
description: |
  Etcd is a high availability key-value store, implementing the RAFT
  algorithm to deal with failover within the etcd cluster. Popular
  as a store of small but important data in distributed systems.
confinement: strict
grade: devel

apps:
  etcd:
    daemon: simple
    command: snap-wrap.sh
    plugs: [ network-bind ]
  etcdctl:
    command: etcdctl
    plugs: [ home, network-bind ]

parts:
  etcd:
    plugin: go
    source: http://github.com/coreos/etcd.git
    go-importpath: github.com/coreos/etcd
    stage:
     - bin/etcd
     - bin/etcdctl
  etcd-wrapper:
    plugin: dump
    source: .
    stage:
      - bin/snap-wrap.sh
      - etcd.conf.yml.sample
