name: etcd
version: '3.0+git'
summary: Resilient key-value store by CoreOS
description: |
  Etcd is a high availability key-value store, implementing the RAFT
  algorithm to deal with failover within the etcd cluster.  Popular
  in the Docker community as a shared store of small but important
  data in a distributed application.
confinement: strict
grade: stable

apps:
  etcd:
    command: snap-wrap.sh
    plugs: [ network-bind ]
  etcdctl:
    command: etcdctl
    plugs: [ home, network-bind ]

parts:
  etcd:
    plugin: go
    source: http://github.com/coreos/etcd.git
    source-tag: release-3.0
    go-importpath: github.com/coreos/etcd
  etcd-wrapper:
    plugin: dump
    source: .
    stage:
      - bin/snap-wrap.sh
      - etcd.conf.yml.sample
