name: etcd
version: '3.1.5'
summary: Resilient key-value store by CoreOS
description: |
  Etcd is a high availability key-value store, implementing the RAFT
  algorithm to deal with failover within the etcd cluster. Popular
  as a store of small but important data in distributed systems.
confinement: strict
grade: stable

# pending a fix to snapd environment variable handling
# environment:
#   ETCDCTL_API: 3

apps:
  etcd:
    daemon: simple
    command: snap-wrap.sh
    plugs: [ network-bind, removable-media ]
  etcdctl:
    command: etcdctl
    plugs: [ home, network-bind ]
    aliases:
      - etcdctl

parts:
  etcd:
    plugin: dump
    source: https://github.com/coreos/etcd/releases/download/v3.1.5/etcd-v3.1.5-linux-amd64.tar.gz
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp etcd $SNAPCRAFT_PART_INSTALL/bin/
      cp etcdctl $SNAPCRAFT_PART_INSTALL/bin/
    stage:
      - bin/etcd
      - bin/etcdctl
  etcd-wrapper:
    plugin: dump
    source: .
    stage:
      - bin/snap-wrap.sh
      - etcd.conf.yml.sample
